const mongoose = require('mongoose');

const articleSchema = new mongoose.Schema({
    title: { type: String, required: true },
    url: { type: String, required: true, unique: true },
    source: { type: String, required: true },
    publishedAt: { type: Date, required: true },
    summary: { type: String }, // Generated by Gemini
    originalText: { type: String }, // Scraped content
    categories: [{ type: String }],
    importanceScore: { type: Number, default: 0 },
    keywords: [{ type: String }],
    status: { type: String, enum: ['Pending', 'Sent', 'Rejected'], default: 'Pending' },
    embedding: { type: [Number], index: '2dsphere' }, // For vector search duplicates
}, { timestamps: true });

// Basic index for faster querying
articleSchema.index({ status: 1, publishedAt: -1 });

module.exports = mongoose.model('Article', articleSchema);
