// generateEmailHTML generates the HTML content for the digest.
const generateEmailHTML = (articles) => {
    let articlesHtml = articles.map(article => `
        <div style="margin-bottom: 30px; border-bottom: 1px solid #eaeaea; padding-bottom: 20px;">
            <h2 style="color: #1a1a1a; margin-bottom: 10px; font-size: 20px;">
                <a href="${article.url}" style="color: #2563eb; text-decoration: none;">${article.title}</a>
            </h2>
            <div style="color: #666; font-size: 12px; margin-bottom: 10px;">
                <strong>Source:</strong> ${article.source} | <strong>Date:</strong> ${new Date(article.publishedAt).toLocaleDateString()}
            </div>
            <p style="color: #444; line-height: 1.6; font-size: 15px;">
                ${article.summary}
            </p>
            <div style="margin-top: 15px;">
                <a href="${article.url}" style="background-color: #2563eb; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; font-size: 14px;">Read More</a>
            </div>
        </div>
    `).join('');

    return `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; background-color: #f9fafb; }
                .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 40px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); margin-top: 40px; margin-bottom: 40px; }
                .header { text-align: center; margin-bottom: 40px; }
                .header h1 { color: #111827; margin: 0; }
                .header p { color: #6b7280; margin-top: 5px; }
                .footer { text-align: center; margin-top: 40px; color: #9ca3af; font-size: 12px; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>AI News Digest</h1>
                    <p>Your curated update on Artificial Intelligence</p>
                </div>
                <div class="content">
                    ${articlesHtml}
                </div>
                <div class="footer">
                    <p>This is an automated digest generated by AI News Portal.</p>
                </div>
            </div>
        </body>
        </html>
    `;
};

module.exports = {
    generateEmailHTML
};
